name: NoSign Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Install CMake
        run: sudo apt-get install -y cmake=3.18.1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          mkdir tempDir
          cd tempDir
          git clone https://github.com/Hicores/QTool
          cd QTool
          export CommitNumber=`git rev-list --count main`
          echo $CommitNumber
          cd ../..
          git submodule update --init --recursive
          echo $CommitNumber
          ./gradlew :QTool:assembleRelease --warning-mode all
